### ISSUE TITLE
LoadError: cannot load such file -- makara/errors/all_connections_blacklisted

### ISSUE THREAD

**Issue by moalamin** [instacart/makara#249]
I am on Rails 5.2.3, OSX 10.15

Here's some of the stack trace:

/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/makara-0.4.1/lib/makara/proxy.rb:154:in `rescue in any_connection'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/makara-0.4.1/lib/makara/proxy.rb:150:in `any_connection'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/makara-0.4.1/lib/makara/proxy.rb:103:in `method_missing'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:849:in `adopt_connection'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:838:in `block in try_to_checkout_new_connection'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:836:in `try_to_checkout_new_connection'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1014:in `retrieve_connection'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:90:in `connection'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/model_schema.rb:466:in `load_schema!'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/attributes.rb:234:in `load_schema!'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/model_schema.rb:459:in `block in load_schema'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/model_schema.rb:456:in `load_schema'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/model_schema.rb:346:in `attribute_types'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/model_schema.rb:370:in `type_for_attribute'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/table_metadata.rb:33:in `type'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/relation/predicate_builder.rb:51:in `build'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/relation/predicate_builder.rb:112:in `block in expand_from_hash'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/relation/predicate_builder.rb:71:in `each'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/relation/predicate_builder.rb:71:in `flat_map'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/relation/predicate_builder.rb:71:in `expand_from_hash'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/relation/where_clause_factory.rb:19:in `build'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/activerecord-5.2.3/lib/active_record/relation/query_methods.rb:50:in `not'
/Users/malamin/Desktop/workspace/law360/app/models/section.rb:58:in `sections'
/Users/malamin/Desktop/workspace/law360/config/routes.rb:301:in `block in core_routes'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
/Users/malamin/.rvm/gems/ruby-2.6.2/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:414:in `draw'
/Users/malamin/Desktop/workspace/law360/config/routes.rb:773:in `block in <top (required)>'

Anyone know how I can fix this or what might be causing the issue? It prevents me from deploying my code or go into rails console. Any help is much appreciated, thanks!

**Comment by admfalko** [comment]
can you show your database.yml file?

**Comment by moalamin** [comment]
> can you show your database.yml file?

development:
    adapter: postgresql_makara
    database: ph_dev
    encoding: utf8
    makara:
        id: postgres
        blacklist_duration: 5
        disable_blacklist: true
        master_ttl: 5
        master_strategy: round_robin
        sticky: true
        connections:
              - role: master
                host: localhost
              - role: slave
                host: localhost


staging: &staging
    adapter: postgresql_makara
    database: ph_staging
    username: rails
    password: ph
    encoding: utf8
    makara:
        id: postgres
        blacklist_duration: 5
        disable_blacklist: true
        master_ttl: 5
        master_strategy: round_robin
        sticky: true
        connections:
              - role: master
                host: ph

staging_from_office: &staging_from_office
    <<: *staging

staging_assets:
    <<: *staging_from_office


production: &production
    adapter: postgresql_makara
    database: ph_production
    username: rails
    password: ph
    encoding: utf8
    makara:
        id: postgres
        blacklist_duration: 5
        disable_blacklist: true
        master_ttl: 0.3
        master_strategy: round_robin
        sticky: true
        connections:
              - role: master
                host: ph
              - role: slave
                host: ph

production_from_office: &production_from_office
    <<: *production

production_assets:
    <<: *production_from_office


load_test: &load_test
    adapter: postgresql_makara
    database: ph_load_test
    username: rails
    password: ph
    encoding: utf8
    makara:
        id: postgres
        blacklist_duration: 5
        disable_blacklist: true
        master_ttl: 5
        master_strategy: round_robin
        sticky: true
        connections:
              - role: master
                host: localhost
              - role: slave
                host: localhost

load_test_from_office: &load_test_from_office
    <<: *load_test

load_test_assets:
    <<: *load_test_from_office

test: &test
    adapter: postgresql_makara
    database: ph_test
    username: rails
    password: ph
    encoding: utf8
    min_messages: warning #removes indexing notices by Postgresql 9+
    makara:
        id: postgres
        blacklist_duration: 5
        disable_blacklist: true
        master_ttl: 5
        master_strategy: round_robin
        sticky: true
        connections:
              - role: master
                host: ph

test_from_office: &test_from_office
    <<: *test

cucumber:
    <<: *test


**I USED ph AS A PLACEHOLDER FOR SENSITIVE INFO**

**Comment by vsrnth** [comment]
I'm running into the same error for the past couple of days.
