### ISSUE TITLE
 wrong number of arguments error with Ruby 3

### ISSUE THREAD

**Issue by ankane** [instacart/makara#276]
Hi, was testing out [distribute_reads](https://github.com/ankane/distribute_reads) with Ruby 3, and it looks like there are some errors related to the keyword arguments changes. Here's a script to reproduce:

```ruby
require "active_record"
require "makara"

ActiveRecord::Base.establish_connection(
  adapter: "postgresql_makara",
  makara: {
    sticky: true,
    connections: [
      {
        role: "master",
        name: "primary",
        database: "distribute_reads_test_primary"
      },
      {
        name: "replica",
        database: "distribute_reads_test_replica"
      }
    ]
  }
)

ActiveRecord::Migration.create_table :users, force: true do |t|
  t.string :name
end
```

And the stack trace:

```text
/Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:296:in `create_table': wrong number of arguments (given 2, expected 1) (ArgumentError)
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/makara-0.4.1/lib/makara/connection_wrapper.rb:99:in `public_send'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/makara-0.4.1/lib/makara/connection_wrapper.rb:99:in `method_missing'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/makara-0.4.1/lib/makara/proxy.rb:105:in `public_send'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/makara-0.4.1/lib/makara/proxy.rb:105:in `block in method_missing'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/makara-0.4.1/lib/makara/proxy.rb:152:in `block in any_connection'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/makara-0.4.1/lib/makara/pool.rb:100:in `block in provide'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/makara-0.4.1/lib/active_record/connection_adapters/makara_abstract_adapter.rb:38:in `handle'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/makara-0.4.1/lib/makara/pool.rb:99:in `provide'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/makara-0.4.1/lib/makara/proxy.rb:151:in `any_connection'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/makara-0.4.1/lib/makara/proxy.rb:103:in `method_missing'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.0/lib/active_record/migration.rb:929:in `block in method_missing'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.0/lib/active_record/migration.rb:897:in `block in say_with_time'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.0/lib/active_record/migration.rb:897:in `say_with_time'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.0/lib/active_record/migration.rb:918:in `method_missing'
  from /Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.0/lib/active_record/migration.rb:658:in `method_missing'
```

**Comment by andrewkendall** [comment]
I'm also seeing the same issue when using Ruby 3.0.0.

**Comment by mlarraz** [comment]
Fixed in https://github.com/instacart/makara/pull/283

**Comment by ankane** [comment]
Thanks @mlarraz, works great!
